development:
  adapter: mysql
  database: breakglass_development
  pool: 5
  username: root
  password:
  host: 127.0.0.1

test:
  adapter: mysql
  database: breakglass_test
  username: root
  password: password
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: breakglass_production
  username: root
  password: 
  socket: /tmp/mysql.sock
